### PR TITLE
Allow configuration of database connection from environment variables

### PR DESCRIPTION
**Pull request by md5**
This PR enables configuring the database connection using the `DATABASE_URL` environment variable.

### CODE REVIEW

**Comment by md5** [comment]
Not sure what the deal is with that CI failure... The `DATABASE_URL` key is single-quoted, so I'm not sure why it's complaining about an undefined constant.

**Comment by c-lliope** [comment]
Hey, @md5 - I haven't seen ERB interpolation in yml files like that - does it work for you locally?

**Comment by md5** [comment]
Yep. It worked for me locally. I used it in order to point to a Dockerized Postgres instances instead of a local one.

The code that does the ERB interpolation for `config/database.yml` is here: https://github.com/rails/rails/blob/1d43458c148f9532a81b92ee3a247da4f1c0b7ad/railties/lib/rails/application/configuration.rb#L85-L110

Pretty much all of the `*.yml` files that Rails uses directly are ERB-interpolated first.

**Comment by md5** [comment]
Also, I just checked the `4-2-stable` branch and confirmed that the same ERB code is there...

**Comment by md5** [comment]
Although now I notice this line... https://github.com/rails/rails/blob/1d43458c148f9532a81b92ee3a247da4f1c0b7ad/railties/lib/rails/application/configuration.rb#L95

**Comment by md5** [comment]
Here's one more place that Rails does ERB interpolation in the `config_for` method: https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/railties/lib/rails/application.rb#L232

**Comment by c-lliope** [comment]
If you try it without this `database.yml` line, does the `DATABASE_URL` env variable still work locally for you? It looks like Rails automatically picks it up on Heroku, so it might do the same thing in development.

**Comment by md5** [comment]
I'll test it out in a couple days once I'm back from vacation. Given the code I found in `configuration.rb`, I think you're right that it should be used automatically.

**Comment by md5** [comment]
Closing this since Rails itself will use `DATABASE_URL` directly if it's present. No need to interpolate into `database.yml`.

From http://guides.rubyonrails.org/configuring.html#configuring-a-database:

> **3.12 Configuring a Database**
> Just about every Rails application will interact with a database. You can connect to the database by setting an environment variable `ENV['DATABASE_URL']` or by using a configuration file called `config/database.yml`.

**Comment by c-lliope** [comment]
:+1:

**Pull request closed without merging**
