### PR TITLE
Working Tags!

### PR DESCRIPTION
**Pull request by robert-baldwin**
Implemented the basic functionality based on the link Becky dropped in Slack.
http://www.reddit.com/r/rails/comments/2chtgw/tagging_in_rails_4/

The front-end could use some work as next steps. The tag on the form wants comma separated tags, while it returns space separated tags on the edit form (confusing!).

@graysonwright @rsiegel827

### CODE REVIEW

**Comment by robert-baldwin** [comment]
Uh oh, Hound doesn't like acts_as_taggable's auto-migrations! :stuck_out_tongue_closed_eyes:

**Comment by c-lliope** [comment]
It looks like the presence validation of tag_list is making the tests fail. I removed that locally, and most tests started to pass.

**Comment by c-lliope** [comment]
Hey, @averon - I just merged this in to the sfbrigade repo so we can all contribute to the branch, and so it's easier to check it out locally.

I invited you to the `sfbrigade` team, so you should have permission to push new commits to the `sfbrigade/tagging` branch. Let me know if you have any trouble!

**Comment by c-lliope** [comment]
Something went weird with the merge, but the commit made it in to PR #36. (commit af8339686435b1ccedf59b866f968a669a806aa6)

**Pull request merged**
